name: zh-CN Translation

on:
  push:
    branches: zh-CN
  pull_request:
    branches: zh-CN

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      uses: actions-rs/install@v0.1
      with:
        crate: mdbook
        version: latest
        use-tool-cache: true
    - name: Install mdbook-linkcheck
      uses: actions-rs/install@v0.1
      with:
        crate: mdbook-linkcheck
        version: 0.7.2
        use-tool-cache: true
    - name: Replace with zh-CN Translation
      run: rm -rf src && mv src_zh-CN src
    - name: Build mdbook
      run: mdbook build && pwd
    - name: Test Examples
      run: cargo test --all --manifest-path=./examples/Cargo.toml --target-dir ./target
    - name: Cache artifact
      uses: actions/upload-artifact@v1
      with:
        name: book
        path: ./book

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get artifact
      uses: actions/download-artifact@v1
      with:
        name: book
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./book/html
        publish_branch: gh-pages
        allow_empty_commit: true
        user_name: "huangjj27"
        user_email: "huangjj.27@qq.com"
        force_orphan: true
